import type { Propiedad, Proyecto } from '@/types'

export const propiedades: Propiedad[] = [
  {
    id: '1',
    slug: 'sky-penthouse-reserve',
    titulo: 'Sky Penthouse Reserve',
    subtitulo: 'Vistas panorámicas sobre el golf de San Isidro',
    ubicacion: 'San Isidro Golf, piso 28',
    distrito: 'San Isidro',
    tipo: 'penthouse',
    operacion: 'venta',
    precio: 1280000,
    moneda: 'USD',
    areaM2: 310,
    dormitorios: 3,
    banos: 3.5,
    estacionamientos: 3,
    descripcion:
      'Penthouse de altura en uno de los edificios más exclusivos de San Isidro Golf. Doble altura en la sala principal, terraza privada con vista 270° al campo de golf y a la ciudad.',
    estado: 'Venta Exclusiva',
    imagen: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    destacada: true,
    caracteristicas: [
      'Terraza privada 85m²',
      'Doble altura en sala',
      'Cocina equipada',
      'Depósito y cuarto de servicio',
      'Seguridad 24/7',
    ],
  },
  {
    id: '2',
    slug: 'villa-lumina',
    titulo: 'Villa Lumina',
    subtitulo: 'Villa contemporánea con jardín y piscina propia',
    ubicacion: 'San Isidro Golf',
    distrito: 'San Isidro',
    tipo: 'casa',
    operacion: 'venta',
    precio: 1450000,
    moneda: 'USD',
    areaM2: 480,
    dormitorios: 4,
    banos: 5,
    estacionamientos: 4,
    descripcion:
      'Villa de diseño contemporáneo en el corazón de San Isidro Golf, con jardín paisajístico, piscina climatizada y cava de vinos.',
    estado: 'Venta Exclusiva',
    imagen: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
    destacada: true,
    caracteristicas: [
      'Piscina climatizada',
      'Cava de vinos',
      'Jardín paisajístico 200m²',
      'Home cinema',
      'Panel solar',
    ],
  },
  {
    id: '3',
    slug: 'garden-residence-malecon',
    titulo: 'Garden Residence Malecón',
    subtitulo: 'Departamento frente al mar con jardín interior',
    ubicacion: 'Malecón, Miraflores',
    distrito: 'Miraflores',
    tipo: 'departamento',
    operacion: 'alquiler',
    precio: 4200,
    moneda: 'USD',
    areaM2: 245,
    dormitorios: 3,
    banos: 3,
    estacionamientos: 2,
    descripcion:
      'Departamento con vista al mar sobre el malecón de Miraflores, jardín interior privado y terraza. A pasos del Parque del Amor.',
    estado: 'Alquiler Prime',
    imagen: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
    destacada: true,
    caracteristicas: [
      'Vista al mar',
      'Jardín interior privado',
      'Terraza 30m²',
      'Amoblado de diseño',
      'Gimnasio en el edificio',
    ],
  },
  {
    id: '4',
    slug: 'the-crown-sky-villa',
    titulo: 'The Crown Sky Villa',
    subtitulo: 'Triplex de autor con piscina infinita en altura',
    ubicacion: 'San Isidro Golf, piso 28 (triplex)',
    distrito: 'San Isidro',
    tipo: 'penthouse',
    operacion: 'venta',
    precio: 3450000,
    moneda: 'USD',
    areaM2: 540,
    dormitorios: 4,
    banos: 5.5,
    estacionamientos: 4,
    descripcion:
      'Triplex de autor que ocupa los tres últimos pisos de la torre, con piscina infinita privada y vista 360° de Lima.',
    estado: 'Disponible',
    imagen: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    destacada: true,
    caracteristicas: [
      'Piscina infinita privada',
      'Ascensor privado',
      'Vista 360°',
      'Diseño de interiores de autor',
      'Bodega de vinos climatizada',
    ],
  },
  {
    id: '5',
    slug: 'villa-solaria-waterfront',
    titulo: 'Villa Solaria Waterfront',
    subtitulo: 'Frente al mar en la costa sur de Lima',
    ubicacion: 'Costa Sur Lima',
    distrito: 'Santiago de Surco',
    tipo: 'casa',
    operacion: 'venta',
    precio: 4800000,
    moneda: 'USD',
    areaM2: 820,
    dormitorios: 5,
    banos: 6,
    estacionamientos: 6,
    descripcion:
      'Villa frente al mar en la costa sur de Lima, con acceso directo a playa privada, piscina infinita y helipuerto.',
    estado: 'Oportunidad de Inversión',
    imagen: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
    destacada: true,
    caracteristicas: [
      'Acceso directo a playa privada',
      'Helipuerto',
      'Piscina infinita frente al mar',
      'Casa de huéspedes independiente',
      'Muelle privado',
    ],
  },
  {
    id: '6',
    slug: 'atelier-miraflores-bay-view',
    titulo: 'Atelier Miraflores Bay View',
    subtitulo: 'Departamento de autor con vista a la bahía',
    ubicacion: 'Malecón, Miraflores, nivel 14',
    distrito: 'Miraflores',
    tipo: 'departamento',
    operacion: 'venta',
    precio: 1920000,
    moneda: 'USD',
    areaM2: 310,
    dormitorios: 3,
    banos: 3.5,
    estacionamientos: 3,
    descripcion:
      'Departamento de autor en uno de los edificios boutique más codiciados de Miraflores, con vista panorámica a la bahía de Lima.',
    estado: 'En Negociación',
    imagen: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
    destacada: true,
    caracteristicas: [
      'Terraza envolvente',
      'Vista a la bahía',
      'Acabados de autor',
      'Depósito incluido',
      'Lobby con concierge',
    ],
  },
]

export const proyectos: Proyecto[] = [
  {
    id: 'p1',
    slug: 'zen-tower-luxury-residences',
    nombre: 'ZEN Tower Luxury Residences',
    distrito: 'San Isidro',
    estado: 'En Construcción',
    precioDesde: 320000,
    niveles: 32,
    unidades: 64,
    unidadesDisponibles: 14,
    avanceConstruccion: 65,
    certificacion: 'LEED Platinum',
    capRate: 14.2,
    descripcion:
      'Torre residencial de 32 niveles con vista al golf, amenities de hotel 5 estrellas y unidades desde 180m².',
    imagen: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
  },
  {
    id: 'p2',
    slug: 'zen-miraflores-bay-residences',
    nombre: 'ZEN Miraflores Bay Residences',
    distrito: 'Miraflores',
    estado: 'Preventa',
    precioDesde: 580000,
    niveles: 18,
    unidades: 36,
    unidadesDisponibles: 22,
    certificacion: 'EDGE Certified',
    capRate: 12.8,
    descripcion:
      'Edificio boutique frente al malecón de Miraflores, con terrazas panorámicas y coworking privado.',
    imagen: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
  },
  {
    id: 'p3',
    slug: 'zen-hacienda-master-plan',
    nombre: 'ZEN Hacienda Master Plan',
    distrito: 'La Molina',
    estado: 'Planos Aprobados',
    precioDesde: 850000,
    niveles: 1,
    unidades: 48,
    unidadesDisponibles: 48,
    certificacion: 'BREEAM In-Use',
    capRate: 11.5,
    descripcion:
      'Lotes desde 600m² hasta 1200m² en una de las zonas más tranquilas y verdes de Lima.',
    imagen: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
  },
]
